shopt -s expand_aliases
#alias ll='ls -l'

# common setting
alias sp='speedtest-cli'

# manual setting
alias ue='cd ../'
alias ueue='cd ../../'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

# history setting
hsearch() { history | grep --color=auto "$1"; } 

# bash setting
alias rr='rm -r'
alias ubash='source ~/.bashrc'
alias ebash='vim ~/.bashrc'
alias ealias='vim ~/.bashrc.d/aliases.sh'
alias h='history | tail -60'

alias lsg='ls | grep'                                                                                                                                                         
alias llg='ll | grep'

# vim setting
alias vi='vim'

# Optional tools (installed by setup.sh --with-tools / --tools-only).
[ ! -f "$HOME/.bash_aliases.tools" ] || source "$HOME/.bash_aliases.tools"
